### ISSUE TITLE
[BUG] Broken Link to Emulsify CLI on Install steps.

### ISSUE THREAD

**Issue by unklCharlos** [emulsify-ds/emulsify-website#122]
**Describe the bug**
Link to Emulsify CLI from Installation page is a broken link.

**To Reproduce**
1. Go to https://www.emulsify.info/docs/emulsify-drupal
2. Click on Requirements > 2. Emulsify CLI

**Expected behavior**
Take user to the new location for Emulsify CLI: https://www.emulsify.info/docs/supporting-projects/emulsify-cli

**Screenshots**
![Screen Shot 2023-08-27 at 1 33 00 PM](https://github.com/emulsify-ds/emulsify-website/assets/42010204/791e0af2-aeb4-4a36-b483-a265b4076ad6)

**Comment by amazingrando** [comment]
@cbfannin I have a PR to fix this at #123. Would you give that a quick review? (The PR has a site spun up, so you won't have to do anything locally.)
